# Generated by Django 3.1.7 on 2021-06-15 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todorest', '0002_auto_20210615_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 0, 23, 46, 782006, tzinfo=utc)),
        ),
    ]
