# Generated by Django 3.1.7 on 2021-06-16 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todorest', '0006_auto_20210615_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 4, 37, 51, 611454, tzinfo=utc)),
        ),
    ]
